services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - ./backend:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./backend:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    ####################################################################################################
    # Redis
    ####################################################################################################
    redis:
        container_name: redis
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
        - .docker/redis/data:/data
        ports:
        - 6379:6379
        links:
        - redis-commander

    ####################################################################################################
    # Redis Commander
    ####################################################################################################
    redis-commander:
      container_name: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
        REDIS_HOSTS: redis
        REDIS_HOST: redis
        REDIS_PORT: redis:6379
        REDIS_PASSWORD: root
        HTTP_USER: root
        HTTP_PASSWORD: root
      ports:
        - 8081:8081
    
    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        container_name: mysql
        image: mysql:8.1
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: refactorian
            MYSQL_USER: refactorian
            MYSQL_PASSWORD: refactorian

    # ####################################################################################################
    # # DATABASE (MariaDB)
    # ####################################################################################################
    # db:
    #     image: mariadb:10.11
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - .docker/db/data:/var/lib/mysql
    #         - .docker/logs:/var/log/mysql
    #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: laravel_db_name
    #         MYSQL_USER: laravel_db_user
    #         MYSQL_PASSWORD: laravel_db_pass

    web:
        build: .docker/vue
        ports:
        - '8082:8082'
        volumes:
        - ./frontend:/app
        